Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).

You have 1 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): main.
Run 'python manage.py migrate' to apply them.
November 14, 2022 - 16:51:53
Django version 3.2.16, using settings 'backend.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).

You have 1 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): main.
Run 'python manage.py migrate' to apply them.
November 14, 2022 - 16:52:14
Django version 3.2.16, using settings 'backend.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Performing system checks...

System check identified no issues (0 silenced).

You have 1 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): main.
Run 'python manage.py migrate' to apply them.
November 14, 2022 - 16:53:26
Django version 3.2.16, using settings 'backend.settings'
Starting development server at http://10.2.0.22:8000/
Quit the server with CONTROL-C.
[2022-11-15 14:25:58 +0100] [16338] [INFO] Starting gunicorn 20.1.0
[2022-11-15 14:25:58 +0100] [16338] [ERROR] Connection in use: ('0.0.0.0', 8000)
[2022-11-15 14:25:58 +0100] [16338] [ERROR] Retrying in 1 second.
[2022-11-15 14:25:59 +0100] [16338] [ERROR] Connection in use: ('0.0.0.0', 8000)
[2022-11-15 14:25:59 +0100] [16338] [ERROR] Retrying in 1 second.
[2022-11-15 14:26:00 +0100] [16338] [ERROR] Connection in use: ('0.0.0.0', 8000)
[2022-11-15 14:26:00 +0100] [16338] [ERROR] Retrying in 1 second.
[2022-11-15 14:26:01 +0100] [16338] [ERROR] Connection in use: ('0.0.0.0', 8000)
[2022-11-15 14:26:01 +0100] [16338] [ERROR] Retrying in 1 second.
[2022-11-15 14:26:02 +0100] [16338] [ERROR] Connection in use: ('0.0.0.0', 8000)
[2022-11-15 14:26:02 +0100] [16338] [ERROR] Retrying in 1 second.
[2022-11-15 14:26:03 +0100] [16338] [ERROR] Can't connect to ('0.0.0.0', 8000)
